// src/AppStyles.js
// Centralized style objects for App.jsx

const styles = {
  appContainer: {
    width: '100vw',
    margin: 0,
    padding: '1rem',
    borderRadius: 24,
    boxSizing: 'border-box',
    background: 'linear-gradient(135deg, #e3f0ff 0%, #f9fbe7 100%)',
    fontSize: '1.1em',
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    justifyContent: 'flex-end',
    position: 'relative',
    boxShadow: '0 8px px rgba(44, 62, 80, 0.12)',
  },
  settingsButton: {
    background: '#eee',
    border: 'none',
    borderRadius: '50%',
    width: 48,
    height: 48,
    fontSize: '1.5em',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
  },
  settingsModalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100vw',
    height: '100vh',
    background: 'rgba(44,62,80,0.10)',
    zIndex: 100,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  settingsModalCard: {
    background: '#fff',
    borderRadius: 16,
    boxShadow: '0 4px 24px rgba(44,62,80,0.12)',
    padding: '2rem 1.5rem 1.5rem 1.5rem',
    minWidth: 300,
    maxWidth: '90vw',
    position: 'relative',
    border: '1px solid #e3eafc',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  closeButton: {
    position: 'absolute',
    top: 14,
    right: 14,
    background: '#e3eafc',
    border: 'none',
    borderRadius: '50%',
    width: 32,
    height: 32,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    color: '#1976d2',
    boxShadow: '0 1px 4px #e3eafc',
    transition: 'background 0.2s',
    padding: 0,
  },
  header: {
    fontSize: '1.7em',
    textAlign: 'center',
    marginBottom: '1rem',
    marginTop: 0,
    color: '#1976d2',
    letterSpacing: '1px',
    textShadow: '0 2px 8px #e3eafc',
  },
  verbDisplay: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 0,
    width: '100%',
  },
  verbText: {
    display: 'block',
    width: '100%',
    fontSize: '2.6em',
    fontWeight: 'bold',
    color: '#1976d2',
    letterSpacing: '1px',
    textShadow: '0 4px 16px #b3c6ff',
    textAlign: 'center',
    transition: 'transform 0.3s',
  },
  verbTranslation: {
    color: '#888',
    fontStyle: 'italic',
    fontSize: '1.2em',
    marginTop: 8,
  },
  nextOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    width: '100%',
    background: 'rgba(25, 118, 210, 0.08)',
    color: '#1976d2',
    textAlign: 'center',
    fontSize: '1.2em',
    fontWeight: 'bold',
    padding: '18px 0',
    borderRadius: '0 0 24px 24px',
    cursor: 'pointer',
    zIndex: 2,
    boxShadow: '0 -2px 8px #e3eafc',
    userSelect: 'none',
  },
  // Button styles for preposition/case choices
  choiceButton: {
    borderRadius: '4px',
    padding: '16px 0',
    cursor: 'pointer',
    outline: 'none',
    width: '100%',
    fontSize: '1.2em',
    transition: 'background 0.2s, border 0.2s',
  },
  // Guess button
  guessButton: {
    width: '100%',
    padding: '16px 0',
    fontSize: '1.2em',
    borderRadius: 4,
    border: '1px solid #1976d2',
    background: '#1976d2',
    color: '#fff',
    fontWeight: 'bold',
    cursor: 'pointer',
  },
  // Input field
  prepInput: {
    marginTop: 8,
    width: '100%',
    fontSize: '1.2em',
    padding: '12px',
    borderRadius: 4,
    border: '1px solid #bdbdbd',
  },
  // Progress bar container
  progressBarContainer: {
    width: '100%',
    margin: '1.5rem 0 0 0',
    height: 12,
    background: '#e3eafc',
    borderRadius: 6,
    overflow: 'hidden',
    boxShadow: '0 2px 8px #e3eafc',
  },
  // Progress bar fill
  progressBarFill: {
    height: '100%',
    background: 'linear-gradient(90deg, #1976d2 0%, #388e3c 100%)',
    borderRadius: 6,
    transition: 'width 0.4s',
  },
  // Score text
  scoreText: {
    marginTop: '0.5rem',
    fontSize: '1.1em',
    textAlign: 'center',
    color: '#1976d2',
    fontWeight: 'bold',
  },
  // Feedback container (level 2 answer)
  feedbackContainer: {
    marginTop: '1rem',
    background: '#f9f9f9',
    padding: '1rem',
    borderRadius: 4,
  },
  // Feedback correct/incorrect
  feedbackText: {
    fontWeight: 'bold',
    marginLeft: 8,
  },
  feedbackCorrect: {
    color: 'green',
  },
  feedbackIncorrect: {
    color: 'red',
  },
  feedbackExpected: {
    color: 'blue',
    marginLeft: 8,
  },
  // Example/translation clickable
  exampleTranslation: {
    cursor: 'pointer',
  },
  // Settings select
  settingsSelect: {
    fontSize: '1em',
    padding: '8px 12px',
    borderRadius: 6,
    border: '1px solid #bdbdbd',
    background: '#f7fbff',
    color: '#1976d2',
    width: '100%',
    marginTop: 6,
  },
  // Settings label
  settingsLabel: {
    fontWeight: 'bold',
    marginRight: 8,
    color: '#1976d2',
    fontSize: '1em',
  },
  // Settings heading
  settingsHeading: {
    marginTop: 0,
    color: '#1976d2',
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: '1.2em',
    letterSpacing: '1px',
  },
};

export default styles;
